# Generated by Django 3.2.22 on 2023-11-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('rate', models.FloatField(default=0)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
