# Generated by Django 3.2.22 on 2024-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByElectionCandidate',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ByElectionRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
